// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhUk58EFnWIN25De2HsfEs1zUwGLOwU3U',
    appId: '1:75544526594:web:6d07492af356b0aaef8c1b',
    messagingSenderId: '75544526594',
    projectId: 'parkpaedia',
    authDomain: 'parkpaedia.firebaseapp.com',
    storageBucket: 'parkpaedia.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgnD3jNjXJ4EKG8tUTq0EhexdO5wFwyqY',
    appId: '1:75544526594:android:4c9d6e4c361e3e7bef8c1b',
    messagingSenderId: '75544526594',
    projectId: 'parkpaedia',
    storageBucket: 'parkpaedia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM9KHkpEp2FIk5NfivJL54Hg_RfCmcpmU',
    appId: '1:75544526594:ios:d2efce94ce95fedbef8c1b',
    messagingSenderId: '75544526594',
    projectId: 'parkpaedia',
    storageBucket: 'parkpaedia.firebasestorage.app',
    iosBundleId: 'com.example.parkpaedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM9KHkpEp2FIk5NfivJL54Hg_RfCmcpmU',
    appId: '1:75544526594:ios:d2efce94ce95fedbef8c1b',
    messagingSenderId: '75544526594',
    projectId: 'parkpaedia',
    storageBucket: 'parkpaedia.firebasestorage.app',
    iosBundleId: 'com.example.parkpaedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhUk58EFnWIN25De2HsfEs1zUwGLOwU3U',
    appId: '1:75544526594:web:924b84d5f77c6fb7ef8c1b',
    messagingSenderId: '75544526594',
    projectId: 'parkpaedia',
    authDomain: 'parkpaedia.firebaseapp.com',
    storageBucket: 'parkpaedia.firebasestorage.app',
  );

}