# .github/workflows/pages.yml
name: Deploy Landing Page

on:
  push:
    branches:
      - main

jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3

      # Package and upload the landingpage folder as-is
      - uses: actions/upload-pages-artifact@v1
        with:
          path: landingpage

      - uses: actions/deploy-pages@v1
